services:
    purethink_user.registration.form.type:
        class: Purethink\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: purethink_user_registration }