<?php

namespace My\FileBundle\Repository;

use My\BackendBundle\Repository\FilterRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends FilterRepository
{
    /**
     * Get files
     *
     * @param string $order
     * @param string $sequence
     * @param string $filter
     * @param string $groupId
     * @return array
     */
	public function getFilesQB($order, $sequence, $filter, $groupId)
	{
		$qb = $this->createQueryBuilder('a')
            ->join('a.series', 's');

        $this->addNameFilterQB($qb, $filter);
        $this->addGroupFilterQB($qb, $groupId);

        $qb->orderBy($order, $sequence);

		return $qb->getQuery();
	}

    public function getFilesByIds(array $ids)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.id IN (:ids)')
            ->setParameter('ids', $ids);

        return $qb->getQuery()->getResult();
    }
}
