<?php

namespace My\FileBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    /**
     * Get files
     *
     * @param string $order
     * @param string $sequence
     * @param string $filtr
     * @param string $groupId
     * @return array
     */
	public function getFiles($order, $sequence, $filtr, $groupId)
	{
		$qb = $this->createQueryBuilder('a')
            ->leftJoin('a.series', 's')
            ->where('a.name LIKE :filtr')
            ->setParameter('filtr', '%'.$filtr.'%');

        if ($groupId) {
            $qb->andWhere('s.id = :groupId')
                ->setParameter('groupId', $groupId);
        }

        $qb->orderBy($order, $sequence);

		return $qb->getQuery();
	}
}
