services:
    sitemap_article_provider:
        class: Purethink\CMSBundle\Sitemap\Article
        arguments: [@router, @doctrine.orm.entity_manager]
        tags:
            -  { name: sitemap.provider }

    purethink.cms.article_type:
        class: Purethink\CMSBundle\Form\Type\ArticleType
        tags:
            - { name: form.type, alias: Article }

    purethink.cms.file_type:
        class: Purethink\CMSBundle\Form\Type\FileType
        tags:
            - { name: form.type, alias: File }

    purethink.cms.language_service:
        class: Purethink\CMSBundle\Service\Language
        arguments: [@doctrine.orm.entity_manager]

    purethink.cms.article_service:
        class: Purethink\CMSBundle\Service\Article
        arguments: [@doctrine.orm.entity_manager]

    purethink.cms.menu_service:
        class: Purethink\CMSBundle\Service\Menu
        arguments: [@doctrine.orm.entity_manager]