services:
    sitemap_article_provider:
        class: Purethink\CMSBundle\Sitemap\Article
        arguments: [@router, @doctrine.orm.entity_manager]
        tags:
            -  { name: sitemap.provider }

    purethink.cms.leftMenu.service:
        class: Purethink\CMSBundle\Service\LeftMenuService
        arguments: [@doctrine.orm.entity_manager, @templating]

    purethink.cms.article_type:
        class: Purethink\CMSBundle\Form\Type\ArticleType
        tags:
            - { name: form.type, alias: Article }

    purethink.cms.file_type:
        class: Purethink\CMSBundle\Form\Type\FileType
        tags:
            - { name: form.type, alias: File }