My\BackendBundle\Entity\Metadata:
    properties:
        title:
            - NotBlank: { groups: [website] }
            - Length:
                max: 255
        description:
            - Length:
                max: 255
        keyword:
            - Length:
                max: 255