# app/config/config.yml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            oneLocale:
                class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            sluggable: true
            sortable: true
            softdeleteable: true
            translatable: true

pix_sortable_behavior:
    position_field: ~

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     AppBundle\Entity\User
    group:
        group_class:   AppBundle\Entity\Group
    from_email:
        address: "%mailer_user%"
        sender_name: PureThink

sonata_admin:
    title: PureThink
    templates:
        layout: ":Admin:layout.html.twig"
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            sonata.admin.group.content:
                label: CMS
                icon: <i class="fa fa-th"></i>
                label_catalogue: AppBundle
                items:
                    - app.admin.article
                    - app.admin.menu_type
                    - app.admin.extension
                    - app.admin.component
                    - sonata.media.admin.media
            sonata.admin.group.administration:
                label: sonata_administration
                icon: <i class="fa fa-cogs"></i>
                label_catalogue: SonataAdminBundle
                items:
                    - sonata.user.admin.user
                    - app.admin.language
                    - app.admin.site

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.text:
        sonata.user.block.account:
        sonata.user.block.menu:
            contexts: [user]
        app.block.language:
        app.block.menu:
        app.block.component:

sonata_media:
    class:
        media: AppBundle\Entity\Media
        gallery: AppBundle\Entity\Gallery
        gallery_has_media: AppBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100, quality: 70 }
                big:   { width: 500, quality: 70 }
                banner:   { width: 1000, quality: 90 }
                news: { width: 104, quality: 90 }
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

sonata_user:
    class:
        user: AppBundle\Entity\User
        group: AppBundle\Entity\Group
    admin:
        user:
            class: AppBundle\Admin\UserAdmin
    impersonating:
        route: page
        parameters: { path: / }

    manager_type: orm

    profile:
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_change_password', label: 'change_password', domain: 'SonataUserBundle'}
        form:
            type: sonata_user_profile
            handler: sonata.user.profile.form.handler.default
            name: sonata_user_profile_form
            validation_groups:
                - Profile
                - Default

ivory_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: "cke_toolbar"
            height: "400px"
            filebrowserBrowseRoute: admin_app_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_app_media_ckeditor_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_app_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_app_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
        excerpt:
            toolbar: "cke_toolbar"
            height: "200px"
            filebrowserBrowseRoute: admin_app_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_app_media_ckeditor_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_app_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_app_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
    toolbars:
        configs:
            cke_toolbar : ['@clipboard', '@editing', '@links', '@insert', '@tools', '@document', '/', '@basicstyles', '@paragraph', '@styles', '@colors']
        items:
            clipboard   : ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
            editing     : ['Scayt']
            links       : ['Link', 'Unlink', 'Anchor']
            insert      : ['Image', 'Table', 'HorizontalRule',  'SpecialChar']
            tools       : ['Maximize']
            document    : ['Source']
            basicstyles : ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat']
            paragraph   : ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft',  'JustifyCenter', 'JustifyRight', 'JustifyBlock']
            styles      : ['Styles', 'Format']
            colors      : ['TextColor', 'BGColor']

a2lix_i18n_doctrine:
    manager_registry: doctrine

a2lix_translation_form:
    locales: [pl, en]

khepin_yaml_fixtures:
    resources:
        - AppBundle/user
        - AppBundle/media
        - AppBundle/language
        - AppBundle/article
        - AppBundle/articleTranslation
        - AppBundle/extension
        - AppBundle/extensionHasField
        - AppBundle/component
        - AppBundle/componentTranslation
        - AppBundle/componentHasElement
        - AppBundle/componentHasText
        - AppBundle/componentHasArticle
        - AppBundle/componentHasFile
        - AppBundle/menuType
        - AppBundle/menuArticle
        - AppBundle/menuTranslation
        - AppBundle
