khepin_yaml_fixtures:
    resources:
        - MyCoreBundle

        - MyUserBundle

        - MyBackendBundle/module
        - MyBackendBundle/menu
        - MyBackendBundle/series
        - MyBackendBundle

        - MyCMSBundle/language
        - MyCMSBundle/article
        - MyCMSBundle/extension
        - MyCMSBundle/extensionHasField
        - MyCMSBundle/component
        - MyCMSBundle/componentHasElement
        - MyCMSBundle/componentHasValue
        - MyCMSBundle

        - MyFileBundle