khepin_yaml_fixtures:
    resources:
        - MyCoreBundle

        - MyUserBundle

        - MyBackendBundle/module
        - MyBackendBundle/menu
        - MyBackendBundle/series
        - MyBackendBundle

        - MyFileBundle

        - MyCMSBundle/language
        - MyCMSBundle/article
        - MyCMSBundle/extension
        - MyCMSBundle/extensionHasField
        - MyCMSBundle/component
        - MyCMSBundle/componentHasElement
        - MyCMSBundle/componentHasText
        - MyCMSBundle/componentHasArticle
        - MyCMSBundle/componentHasFile
        - MyCMSBundle