khepin_yaml_fixtures:
    resources:
        - MyCoreBundle

        - MyUserBundle/group
        - MyUserBundle/user

        - MyAdminBundle/module
        - MyAdminBundle/menu
        - MyAdminBundle/series
        - MyAdminBundle

        - MyFileBundle

        - MyCMSBundle/language
        - MyCMSBundle/article
        - MyCMSBundle/extension
        - MyCMSBundle/extensionHasField
        - MyCMSBundle/component
        - MyCMSBundle/componentHasElement
        - MyCMSBundle/componentHasText
        - MyCMSBundle/componentHasArticle
        - MyCMSBundle/componentHasFile
        - MyCMSBundle