khepin_yaml_fixtures:
    resources:
        - MyCoreBundle

        - MyUserBundle

        - MyBackendBundle/module
        - MyBackendBundle/menu
        - MyBackendBundle/series
        - MyBackendBundle

        - MyCMSBundle/language
        - MyCMSBundle/article
        - MyCMSBundle/extension
        - MyCMSBundle/componentHasColumn
        - MyCMSBundle/componentOnPage
        - MyCMSBundle/componentOnPageHasElement
        - MyCMSBundle/componentOnPageHasValue
        - MyCMSBundle

        - MyFileBundle