khepin_yaml_fixtures:
    resources:
        - PurethinkCoreBundle

        - PurethinkUserBundle/group
        - PurethinkUserBundle/user

        - PurethinkAdminBundle/module
        - PurethinkAdminBundle/menu
        - PurethinkAdminBundle/series
        - PurethinkAdminBundle

        - PurethinkFileBundle

        - PurethinkCMSBundle/language
        - PurethinkCMSBundle/article
        - PurethinkCMSBundle/extension
        - PurethinkCMSBundle/extensionHasField
        - PurethinkCMSBundle/component
        - PurethinkCMSBundle/componentHasElement
        - PurethinkCMSBundle/componentHasText
        - PurethinkCMSBundle/componentHasArticle
        - PurethinkCMSBundle/componentHasFile
        - PurethinkCMSBundle