khepin_yaml_fixtures:
    resources:
        - ApplicationSonataUserBundle/user

        - PurethinkCoreBundle

        - PurethinkFileBundle

        - PurethinkCMSBundle/Metadata
        - PurethinkCMSBundle/language
        - PurethinkCMSBundle/article
        - PurethinkCMSBundle/extension
        - PurethinkCMSBundle/extensionHasField
        - PurethinkCMSBundle/component
        - PurethinkCMSBundle/componentHasElement
        - PurethinkCMSBundle/componentHasText
        - PurethinkCMSBundle/componentHasArticle
        - PurethinkCMSBundle/componentHasFile
        - PurethinkCMSBundle/menuType
        - PurethinkCMSBundle/menu
        - PurethinkCMSBundle