purethink_core:
    resource: "@PurethinkCoreBundle/Resources/config/routing.yml"

purethink_admin:
    resource: "@PurethinkAdminBundle/Resources/config/routing.yml"

purethink_cms:
    resource: "@PurethinkCMSBundle/Resources/config/routing.yml"