fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

kphoen_sitemap:
    resource: "@KPhoenSitemapBundle/Resources/config/routing.yml"

my_core:
    resource: "@MyCoreBundle/Controller/"
    type:     annotation
    prefix:   /

my_user:
    resource: "@MyUserBundle/Controller/"
    type:     annotation
    prefix:   /

my_file:
    resource: "@MyFileBundle/Controller/"
    type:     annotation
    prefix:   /admin/file

my_cms:
    resource: "@MyCMSBundle/Controller/"
    type:     annotation
    prefix:   /

my_backend:
    resource: "@MyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin