purethink_core:
    resource: "@PurethinkCoreBundle/Resources/config/routing.yml"

purethink_admin:
    resource: "@PurethinkAdminBundle/Resources/config/routing.yml"

purethink_cms:
    resource: "@PurethinkCMSBundle/Resources/config/routing.yml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
