admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type: sonata_admin

soanata_user_admin:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'