security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    access_decision_manager:
        strategy: consensus

    firewalls:
        admin:
              pattern:            /admin(.*)
              context:            user
              form_login:
                  provider:       fos_userbundle
                  login_path:     /admin/login
                  use_forward:    false
                  check_path:     /admin/login_check
                  failure_path:   null
              logout:
                  path:           /admin/logout
                  invalidate_session: false
              anonymous:          true
        main:
            pattern: ^/
            switch_user: true
            context:     user
            logout:
                invalidate_session: false
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]