services:
    my.pagination.service:
        class: My\AdminBundle\Service\PaginationService
        arguments: [@knp_paginator]

    my.admin.type.metadata:
        class: My\AdminBundle\Form\MetadataType
        tags:
            - { name: form.type, alias: metadata }

    my.admin.type.series:
        class: My\AdminBundle\Form\Type\SeriesType
        tags:
            - { name: form.type, alias: series }