sonata_admin:
    title: %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%

    security:
        handler: sonata.admin.security.handler.acl

    templates:
        layout: SonataAdminBundle::layout.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> You can customize this dashboard by editing the sonata_admin.yml file. The current dashboard presents the recent items from the NewsBundle and a timeline with the latest action"} }
