sonata_admin:
    title: PureThink

    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            sonata.admin.group.content:
                label: CMS
                icon: <i class="fa fa-th"></i>
                label_catalogue: PurethinkCMSBundle
                items:
                    - purethink_cms.admin.article
                    - purethink_cms.admin.menu_type
                    - purethink_cms.admin.extension
                    - purethink_cms.admin.component
                    - sonata.media.admin.media
            sonata.admin.group.administration:
                label: sonata_administration
                icon: <i class="fa fa-cogs"></i>
                label_catalogue: SonataAdminBundle
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - purethink_cms.admin.language
                    - purethink_cms.admin.site
