<?php

namespace My\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function getMenuForModule($moduleId)
    {
        $qb = $this->createQueryBuilder('m')
            ->where('m.module = :moduleId')
            ->orderBy('m.sequence')
            ->setParameter('moduleId', $moduleId);

        return $qb->getQuery()->getResult();
    }
}
