<?php

namespace My\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends EntityRepository
{
    public function getGroupsByMenuIdQb($menuId)
    {
        return $this->createQueryBuilder('s')
            ->join('s.menu', 'm')
            ->where('m.id = :menu_id')
            ->orderBy('s.name')
            ->setParameter('menu_id', $menuId);
    }

    public function getGroupsByMenuId($menuId)
    {
        return $this->getGroupsByMenuIdQb($menuId)->getQuery()->getResult();
    }
}
