<?php

namespace My\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
	/**
	 * Get nenu
	 * 
	 * @param integer $moduleId
	 * @return array
	 */
	public function getMenu($moduleId)
	{
		$qb = $this->createQueryBuilder('m')
			->leftJoin('m.module', 'mod')
			->where('mod.id = :module_id')
			->orderBy('m.sequence')
		    ->setParameter('module_id', $moduleId);

		return $qb->getQuery()->getResult();
	}
}
