<?php

namespace My\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSArticleRepository extends EntityRepository
{
    /**
     * Get articles
     *
     * @param string $order
     * @param string $sequence
     * @param string $filtr
     * @return array
     */
	public function getArticles($order, $sequence, $filtr)
	{
		$qb = $this->createQueryBuilder('a')
            ->where('a.name LIKE :filtr')
            ->setParameter('filtr', '%'.$filtr.'%')
            ->orderBy($order, $sequence);
			// ->leftJoin('a.language', 'l')
			// ->where('mod.id = :module_id')
		 //    ->setParameter('module_id', $moduleId)
			// ->orderBy('m.sequence');

		return $qb->getQuery();
	}
}
