<?php

namespace My\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSArticleRepository extends EntityRepository
{
	public function getArticles()
	{
		$qb = $this->createQueryBuilder('a');
			// ->leftJoin('a.language', 'l')
			// ->where('mod.id = :module_id')
		 //    ->setParameter('module_id', $moduleId)
			// ->orderBy('m.sequence');

		return $qb->getQuery()->getResult();
	}
}
