<?php

namespace My\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CMSComponentOnPageHasValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSComponentOnPageHasValueRepository extends EntityRepository
{
    /**
     * Get elements
     *
     * @param string $order
     * @param string $sequence
     * @param string $filtr
     * @param integer $componentId
     * @return array
     */
    public function getElements($order, $sequence, $filtr, $componentId)
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.componentOnPageHasElement', 'cophe')
            ->leftJoin('a.componentOnPageHasColumn', 'cophc');
            // ->where('a.name LIKE :filtr')
            // ->setParameter('filtr', '%'.$filtr.'%');

        // $qb->orderBy($order, $sequence);

        return $qb->getQuery();
    }
}