<?php

namespace My\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CMSComponentHasColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSComponentHasColumnRepository extends EntityRepository
{
    /**
     * Get columns
     *
     * @param string $order
     * @param string $sequence
     * @param string $filtr
     * @param integer $componentId
     * @return array
     */
	public function getColumns($order, $sequence, $filtr, $componentId)
	{
		$qb = $this->createQueryBuilder('a')
            ->select('a')
            ->addSelect('ct')
            ->leftJoin('a.component', 'c')
            ->leftJoin('a.columnType', 'ct')
            ->where('c.id = :componentId')
            ->setParameter('componentId', $componentId)
            ->andWhere('a.name LIKE :filtr')
            ->setParameter('filtr', '%'.$filtr.'%');

        $qb->orderBy($order, $sequence);

		return $qb->getQuery();
	}
}
