<?php

namespace My\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CMSComponentOnPageHasValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSComponentOnPageHasValueRepository extends EntityRepository
{
    /**
     * Get elements
     *
     * @param string $order
     * @param string $sequence
     * @param string $filtr
     * @param integer $componentId
     * @return array
     */
    public function getElements($order, $sequence, $filtr, $componentId)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a, a.content')
            ->addSelect('cophe.id, cophe.createdAt, cophe.updatedAt')
            ->leftJoin('a.componentOnPageHasElement', 'cophe')
            ->leftJoin('a.componentHasColumn', 'chc')
            ->where('chc.isMainField = true')
            ->andWhere('a.content LIKE :filtr')
            ->setParameter('filtr', '%'.$filtr.'%');

        // $qb->orderBy($order, $sequence);

        $qb->groupBy('a.componentOnPageHasElement');

        return $qb->getQuery();
    }
}