<?php

namespace My\CMSBundle\Repository;

use My\BackendBundle\Repository\FilterRepository;

/**
 * CMSTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSTemplateRepository extends FilterRepository
{
    /**
     * Get templates
     *
     * @param string $order
     * @param string $sequence
     * @param string $filter
     * @return array
     */
    public function getTemplatesQB($order, $sequence, $filter)
    {
        $qb = $this->createQueryBuilder('a');

        $this->addNameFilterQB($qb, $filter);

        $qb->orderBy($order, $sequence);

        return $qb->getQuery();
    }
}
