<?php

namespace My\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CMSWebSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSWebSiteRepository extends EntityRepository
{
    /**
     * Get web site
     *
     * @param integer $languageId
     * @return object
     */
    public function getWebSite($languageId)
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.language', 'l')
            ->where('l.id = :languageId')
            ->setParameter('languageId', $languageId)
            ->setMaxResults(1);

        return $qb->getQuery()->getSingleResult();
    }
}
