<?php

namespace My\CMSBundle\Repository;

use My\BackendBundle\Repository\FilterRepository;

/**
 * CMSWebSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMSWebSiteRepository extends FilterRepository
{
    /**
     * Get web site
     *
     * @param integer $languageId
     * @return object
     */
    public function getWebSite($languageId)
    {
        $qb = $this->createQueryBuilder('a')
            ->join('a.language', 'l');

        $this->addLanguageIdFilterQB($qb, $languageId);

        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * Get meta
     *
     * @param string $locale
     * @return object
     */
    public function getMeta($locale)
    {
        $qb = $this->createQueryBuilder('a')
            ->join('a.language', 'l');

        $this->addLanguageAliasFilter($qb, $locale);
        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
