parameters:
    app.menu.classess:
        Article: AppBundle\Entity\MenuArticle
        Url: AppBundle\Entity\MenuUrl

services:
    app.admin.language:
        tags:
            - { name: sonata.admin, manager_type: orm, group: CMS, label: "admin.sidebar.language" }
        class: AppBundle\Admin\LanguageAdmin
        arguments: [null, AppBundle\Entity\Language, SonataAdminBundle:CRUD]

    app.admin.site:
        tags:
            - { name: sonata.admin, manager_type: orm, group: CMS, label: "admin.sidebar.site" }
        class: AppBundle\Admin\SiteAdmin
        arguments: [null, AppBundle\Entity\Site, 'AppBundle:Admin\SiteAdmin']
        calls:
            - [ setLanguageService, ['@app.language_service'] ]

    app.admin.article:
        tags:
            - { name: sonata.admin, manager_type: orm, group: CMS, label: "admin.sidebar.artice" }
        class: AppBundle\Admin\ArticleAdmin
        arguments: [null, AppBundle\Entity\Article, SonataAdminBundle:CRUD]
        calls:
            - [ setSecurityContext, ['@security.context'] ]
            - [ setLanguageService, ['@app.language_service'] ]

    app.admin.menu_type:
        tags:
            - { name: sonata.admin, manager_type: orm, group: CMS, label: "admin.sidebar.menu" }
        class: AppBundle\Admin\MenuTypeAdmin
        arguments: [null, AppBundle\Entity\MenuType, SonataAdminBundle:CRUD]
        calls:
            - [ addChild, ['@app.admin.menu'] ]

    app.admin.menu:
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        class: AppBundle\Admin\MenuAdmin
        arguments: [null, AppBundle\Entity\Menu, SonataAdminBundle:CRUD]
        calls:
            - [ setLanguageService, ['@app.language_service'] ]
            - [ setSubClasses, ['%app.menu.classess%'] ]

    app.admin.extension:
        tags:
            - { name: sonata.admin, manager_type: orm, group: CMS, label: "admin.sidebar.extension" }
        class: AppBundle\Admin\ExtensionAdmin
        arguments: [null, AppBundle\Entity\Extension, SonataAdminBundle:CRUD]

    app.admin.extension_has_field:
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        class: AppBundle\Admin\ExtensionHasFieldAdmin
        arguments: [null, AppBundle\Entity\ExtensionHasField, SonataAdminBundle:CRUD]

    app.admin.component:
        tags:
            - { name: sonata.admin, manager_type: orm, group: CMS, label: "admin.sidebar.component" }
        class: AppBundle\Admin\ComponentAdmin
        arguments: [null, AppBundle\Entity\Component, SonataAdminBundle:CRUD]
        calls:
            - [ addChild, ['@app.admin.component_has_element'] ]

    app.admin.component_has_element:
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        class: AppBundle\Admin\ComponentHasElementAdmin
        arguments: [null, AppBundle\Entity\ComponentHasElement, 'AppBundle:Admin\ComponentHasElementAdmin']
        calls:
            - [ addChild, ['@app.admin.component_has_value'] ]
            - [ setContainer, ['@service_container'] ]
            - [ setPositionService, ['@pix_sortable_behavior.position']]

    app.admin.component_has_value:
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        class: AppBundle\Admin\ComponentHasValueAdmin
        arguments: [null, AppBundle\Entity\ComponentHasValue, SonataAdminBundle:CRUD]
