services:
    app.language.listener:
        class: AppBundle\EventListener\LanguageListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocale }
        arguments: ['@app.language_service']

    sonata.admin.helper:
        class: AppBundle\Admin\AdminHelper
        arguments: ['@sonata.admin.pool']

    sonata.admin.controller.admin:
        class: AppBundle\Controller\HelperController
        arguments: ['@twig', '@sonata.admin.pool', '@sonata.admin.helper', '@validator']

    sonata.admin.form.type.admin:
        class: AppBundle\Form\Type\AdminType
        tags:
            - { name: form.type, alias: sonata_type_admin }

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    app.article_type:
        class: AppBundle\Form\Type\ArticleType
        tags:
            - { name: form.type, alias: Article }

    app.file_type:
        class: AppBundle\Form\Type\FileType
        tags:
            - { name: form.type, alias: File }

    app.language_service:
        class: AppBundle\Service\Language
        arguments: ['@doctrine.orm.entity_manager']