services:
    app.twig.site_extension:
        class: AppBundle\Twig\SiteExtension
        arguments: ['@doctrine.orm.entity_manager']
        public: false
        tags:
            - { name: twig.extension }