services:
    app.twig.site_extension:
        class: AppBundle\Twig\SiteExtension
        arguments: ['@doctrine.orm.entity_manager']
        public: false
        tags:
            - { name: twig.extension }

    app.twig.media_extension:
        class: AppBundle\Twig\MediaExtension
        arguments: ['@kernel', '@sonata.media.twig.extension']
        public: false
        tags:
            - { name: twig.extension }