model: AppBundle\Entity\Site
fixtures:
    cms_site_1:
        language: cms_language_1
        metadata: cms_metadata_1
    cms_site_2:
        language: cms_language_2
        metadata: cms_metadata_2